# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'digital_servos.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DigitalServos(object):
    def setupUi(self, DigitalServos):
        DigitalServos.setObjectName("DigitalServos")
        DigitalServos.resize(379, 431)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_interfaces = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBox_interfaces.setObjectName("comboBox_interfaces")
        self.horizontalLayout.addWidget(self.comboBox_interfaces)
        self.pushButton_scan = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_scan.setObjectName("pushButton_scan")
        self.horizontalLayout.addWidget(self.pushButton_scan)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_servos = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget_servos.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_servos.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_servos.setAlternatingRowColors(True)
        self.tableWidget_servos.setColumnCount(3)
        self.tableWidget_servos.setObjectName("tableWidget_servos")
        self.tableWidget_servos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_servos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_servos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_servos.setHorizontalHeaderItem(2, item)
        self.tableWidget_servos.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget_servos.horizontalHeader().setMinimumSectionSize(30)
        self.verticalLayout.addWidget(self.tableWidget_servos)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_ping = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_ping.setObjectName("pushButton_ping")
        self.horizontalLayout_2.addWidget(self.pushButton_ping)
        self.pushButton_reset = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.horizontalLayout_2.addWidget(self.pushButton_reset)
        self.pushButton_dump = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_dump.setObjectName("pushButton_dump")
        self.horizontalLayout_2.addWidget(self.pushButton_dump)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget_registers = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_registers.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_registers.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_registers.setAlternatingRowColors(True)
        self.tableWidget_registers.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget_registers.setColumnCount(6)
        self.tableWidget_registers.setObjectName("tableWidget_registers")
        self.tableWidget_registers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_registers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_registers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_registers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_registers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_registers.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_registers.setHorizontalHeaderItem(5, item)
        self.tableWidget_registers.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget_registers.horizontalHeader().setMinimumSectionSize(30)
        self.verticalLayout_2.addWidget(self.tableWidget_registers)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        DigitalServos.setWidget(self.dockWidgetContents)

        self.retranslateUi(DigitalServos)
        QtCore.QMetaObject.connectSlotsByName(DigitalServos)

    def retranslateUi(self, DigitalServos):
        _translate = QtCore.QCoreApplication.translate
        DigitalServos.setWindowTitle(_translate("DigitalServos", "Digital Servos"))
        self.label.setText(_translate("DigitalServos", "Interface"))
        self.pushButton_scan.setText(_translate("DigitalServos", "Scan"))
        self.groupBox.setTitle(_translate("DigitalServos", "Servos"))
        item = self.tableWidget_servos.horizontalHeaderItem(0)
        item.setText(_translate("DigitalServos", "ID"))
        item = self.tableWidget_servos.horizontalHeaderItem(1)
        item.setText(_translate("DigitalServos", "Model Name"))
        item = self.tableWidget_servos.horizontalHeaderItem(2)
        item.setText(_translate("DigitalServos", "Status"))
        self.pushButton_ping.setText(_translate("DigitalServos", "Ping"))
        self.pushButton_reset.setText(_translate("DigitalServos", "Reset"))
        self.pushButton_dump.setText(_translate("DigitalServos", "Dump"))
        self.groupBox_2.setTitle(_translate("DigitalServos", "Registers"))
        item = self.tableWidget_registers.horizontalHeaderItem(0)
        item.setText(_translate("DigitalServos", "Area"))
        item = self.tableWidget_registers.horizontalHeaderItem(1)
        item.setText(_translate("DigitalServos", "Access"))
        item = self.tableWidget_registers.horizontalHeaderItem(2)
        item.setText(_translate("DigitalServos", "Address"))
        item = self.tableWidget_registers.horizontalHeaderItem(3)
        item.setText(_translate("DigitalServos", "Size (Bytes)"))
        item = self.tableWidget_registers.horizontalHeaderItem(4)
        item.setText(_translate("DigitalServos", "Name"))
        item = self.tableWidget_registers.horizontalHeaderItem(5)
        item.setText(_translate("DigitalServos", "Value"))

