# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphics.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Graphics(object):
    def setupUi(self, Graphics):
        Graphics.setObjectName("Graphics")
        Graphics.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Graphics)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget_graphics = QtWidgets.QWidget(self.splitter)
        self.widget_graphics.setObjectName("widget_graphics")
        self.widget_parameters = QtWidgets.QWidget(self.splitter)
        self.widget_parameters.setObjectName("widget_parameters")
        self.verticalLayout.addWidget(self.splitter)
        Graphics.setCentralWidget(self.centralwidget)
        self.toolBar_actions = QtWidgets.QToolBar(Graphics)
        self.toolBar_actions.setEnabled(True)
        self.toolBar_actions.setMovable(False)
        self.toolBar_actions.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar_actions.setFloatable(False)
        self.toolBar_actions.setObjectName("toolBar_actions")
        Graphics.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_actions)
        self.actionPan = QtWidgets.QAction(Graphics)
        self.actionPan.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/silk/cursor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPan.setIcon(icon)
        self.actionPan.setObjectName("actionPan")
        self.actionGoto = QtWidgets.QAction(Graphics)
        self.actionGoto.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/silk/car.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGoto.setIcon(icon1)
        self.actionGoto.setObjectName("actionGoto")
        self.actionZoom = QtWidgets.QAction(Graphics)
        self.actionZoom.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/silk/magnifier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom.setIcon(icon2)
        self.actionZoom.setObjectName("actionZoom")
        self.actionStop = QtWidgets.QAction(Graphics)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/silk/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon3)
        self.actionStop.setObjectName("actionStop")
        self.actionColor = QtWidgets.QAction(Graphics)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/silk/tag_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionColor.setIcon(icon4)
        self.actionColor.setObjectName("actionColor")
        self.actionRestart = QtWidgets.QAction(Graphics)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/silk/control_start_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRestart.setIcon(icon5)
        self.actionRestart.setObjectName("actionRestart")
        self.actionStartPause = QtWidgets.QAction(Graphics)
        self.actionStartPause.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/silk/control_pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icons/silk/control_play_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStartPause.setIcon(icon6)
        self.actionStartPause.setObjectName("actionStartPause")
        self.actionViewSettings = QtWidgets.QAction(Graphics)
        self.actionViewSettings.setCheckable(True)
        self.actionViewSettings.setChecked(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/silk/cog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionViewSettings.setIcon(icon7)
        self.actionViewSettings.setObjectName("actionViewSettings")
        self.actionViewGraphs = QtWidgets.QAction(Graphics)
        self.actionViewGraphs.setCheckable(True)
        self.actionViewGraphs.setChecked(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/silk/chart_curve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionViewGraphs.setIcon(icon8)
        self.actionViewGraphs.setObjectName("actionViewGraphs")
        self.toolBar_actions.addAction(self.actionPan)
        self.toolBar_actions.addAction(self.actionZoom)
        self.toolBar_actions.addSeparator()
        self.toolBar_actions.addAction(self.actionGoto)
        self.toolBar_actions.addAction(self.actionStop)
        self.toolBar_actions.addSeparator()
        self.toolBar_actions.addAction(self.actionColor)
        self.toolBar_actions.addAction(self.actionRestart)
        self.toolBar_actions.addAction(self.actionStartPause)
        self.toolBar_actions.addSeparator()
        self.toolBar_actions.addAction(self.actionViewSettings)
        self.toolBar_actions.addAction(self.actionViewGraphs)

        self.retranslateUi(Graphics)
        QtCore.QMetaObject.connectSlotsByName(Graphics)

    def retranslateUi(self, Graphics):
        _translate = QtCore.QCoreApplication.translate
        Graphics.setWindowTitle(_translate("Graphics", "graphics"))
        self.toolBar_actions.setWindowTitle(_translate("Graphics", "Graphics toolbar"))
        self.actionPan.setText(_translate("Graphics", "Pan"))
        self.actionPan.setToolTip(_translate("Graphics", "Switch to Pan mode"))
        self.actionGoto.setText(_translate("Graphics", "Goto"))
        self.actionZoom.setText(_translate("Graphics", "Zoom"))
        self.actionZoom.setToolTip(_translate("Graphics", "Switch to Zoom mode"))
        self.actionStop.setText(_translate("Graphics", "Stop"))
        self.actionStop.setToolTip(_translate("Graphics", "Cancel any motion"))
        self.actionColor.setText(_translate("Graphics", "Color"))
        self.actionColor.setToolTip(_translate("Graphics", "Select match color"))
        self.actionRestart.setText(_translate("Graphics", "Restart"))
        self.actionRestart.setToolTip(_translate("Graphics", "Restart match sequence"))
        self.actionStartPause.setText(_translate("Graphics", "StartPause"))
        self.actionStartPause.setToolTip(_translate("Graphics", "Start or pause match sequence"))
        self.actionViewSettings.setText(_translate("Graphics", "ViewSettings"))
        self.actionViewSettings.setToolTip(_translate("Graphics", "Show / Hide graphics settings"))
        self.actionViewGraphs.setText(_translate("Graphics", "ViewGraphs"))
        self.actionViewGraphs.setToolTip(_translate("Graphics", "Show / Hide graphics windows"))
