# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imcc.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph.Qt import QtCore, QtGui
from pyqtgraph.dockarea import *

class Ui_imcc(object):
    def setupUi(self, imcc):
        imcc.setObjectName("imcc")
        imcc.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/robot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        imcc.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(imcc)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = DockArea(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        imcc.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(imcc)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuConfig = QtWidgets.QMenu(self.menubar)
        self.menuConfig.setObjectName("menuConfig")
        imcc.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(imcc)
        self.statusbar.setObjectName("statusbar")
        imcc.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(imcc)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.NoToolBarArea)
        self.toolBar.setIconSize(QtCore.QSize(24, 24))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        imcc.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionConnect = QtWidgets.QAction(imcc)
        self.actionConnect.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/silk/disconnect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icons/silk/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionConnect.setIcon(icon1)
        self.actionConnect.setObjectName("actionConnect")
        self.actionConfigLoad = QtWidgets.QAction(imcc)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/fugue/icons/folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfigLoad.setIcon(icon2)
        self.actionConfigLoad.setObjectName("actionConfigLoad")
        self.actionConfigSave = QtWidgets.QAction(imcc)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/fugue/icons/disk-black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfigSave.setIcon(icon3)
        self.actionConfigSave.setObjectName("actionConfigSave")
        self.actionViewConsole = QtWidgets.QAction(imcc)
        self.actionViewConsole.setCheckable(True)
        self.actionViewConsole.setChecked(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/silk/application_xp_terminal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionViewConsole.setIcon(icon4)
        self.actionViewConsole.setObjectName("actionViewConsole")
        self.actionViewBootload = QtWidgets.QAction(imcc)
        self.actionViewBootload.setCheckable(True)
        self.actionViewBootload.setChecked(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/silk/computer_go.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionViewBootload.setIcon(icon5)
        self.actionViewBootload.setObjectName("actionViewBootload")
        self.actionReset = QtWidgets.QAction(imcc)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/silk/arrow_rotate_anticlockwise.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReset.setIcon(icon6)
        self.actionReset.setObjectName("actionReset")
        self.actionProbe = QtWidgets.QAction(imcc)
        self.actionProbe.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/silk/application_go.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProbe.setIcon(icon7)
        self.actionProbe.setObjectName("actionProbe")
        self.actionViewParameters = QtWidgets.QAction(imcc)
        self.actionViewParameters.setCheckable(True)
        self.actionViewParameters.setChecked(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/silk/cog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionViewParameters.setIcon(icon8)
        self.actionViewParameters.setObjectName("actionViewParameters")
        self.actionViewVariables = QtWidgets.QAction(imcc)
        self.actionViewVariables.setCheckable(True)
        self.actionViewVariables.setChecked(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/silk/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionViewVariables.setIcon(icon9)
        self.actionViewVariables.setObjectName("actionViewVariables")
        self.actionPan = QtWidgets.QAction(imcc)
        self.actionPan.setCheckable(True)
        self.actionPan.setChecked(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/silk/cursor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPan.setIcon(icon10)
        self.actionPan.setObjectName("actionPan")
        self.actionGoto = QtWidgets.QAction(imcc)
        self.actionGoto.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/silk/car.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGoto.setIcon(icon11)
        self.actionGoto.setObjectName("actionGoto")
        self.actionZoom = QtWidgets.QAction(imcc)
        self.actionZoom.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/silk/magnifier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom.setIcon(icon12)
        self.actionZoom.setObjectName("actionZoom")
        self.actionStopMotion = QtWidgets.QAction(imcc)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/fugue/icons/minus-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStopMotion.setIcon(icon13)
        self.actionStopMotion.setObjectName("actionStopMotion")
        self.actionColor = QtWidgets.QAction(imcc)
        self.actionColor.setCheckable(True)
        self.actionColor.setChecked(False)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/fugue/icons/flag-blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionColor.setIcon(icon14)
        self.actionColor.setObjectName("actionColor")
        self.actionStart = QtWidgets.QAction(imcc)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/silk/control_play_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon15)
        self.actionStart.setObjectName("actionStart")
        self.actionPauseResume = QtWidgets.QAction(imcc)
        self.actionPauseResume.setCheckable(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/silk/control_pause_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon16.addPixmap(QtGui.QPixmap(":/icons/silk/control_pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPauseResume.setIcon(icon16)
        self.actionPauseResume.setObjectName("actionPauseResume")
        self.actionViewSettings = QtWidgets.QAction(imcc)
        self.actionViewSettings.setCheckable(True)
        self.actionViewSettings.setChecked(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/silk/chart_bar_link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionViewSettings.setIcon(icon17)
        self.actionViewSettings.setObjectName("actionViewSettings")
        self.actionViewGraphs = QtWidgets.QAction(imcc)
        self.actionViewGraphs.setCheckable(True)
        self.actionViewGraphs.setChecked(True)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/silk/chart_curve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionViewGraphs.setIcon(icon18)
        self.actionViewGraphs.setObjectName("actionViewGraphs")
        self.actionViewDigital_Servos = QtWidgets.QAction(imcc)
        self.actionViewDigital_Servos.setCheckable(True)
        self.actionViewDigital_Servos.setChecked(True)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/silk/controller.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionViewDigital_Servos.setIcon(icon19)
        self.actionViewDigital_Servos.setObjectName("actionViewDigital_Servos")
        self.actionPower_ON = QtWidgets.QAction(imcc)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/fugue/icons/tick-circle-frame.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPower_ON.setIcon(icon20)
        self.actionPower_ON.setObjectName("actionPower_ON")
        self.actionPower_OFF = QtWidgets.QAction(imcc)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/fugue/icons/exclamation-red-frame.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPower_OFF.setIcon(icon21)
        self.actionPower_OFF.setObjectName("actionPower_OFF")
        self.actionStop = QtWidgets.QAction(imcc)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icons/silk/control_stop_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon22)
        self.actionStop.setObjectName("actionStop")
        self.actionInit = QtWidgets.QAction(imcc)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icons/silk/house_go.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInit.setIcon(icon23)
        self.actionInit.setObjectName("actionInit")
        self.actionViewSequencer = QtWidgets.QAction(imcc)
        self.actionViewSequencer.setCheckable(True)
        self.actionViewSequencer.setChecked(True)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/icons/silk/script.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionViewSequencer.setIcon(icon24)
        self.actionViewSequencer.setObjectName("actionViewSequencer")
        self.menuConfig.addAction(self.actionConfigLoad)
        self.menuConfig.addAction(self.actionConfigSave)
        self.menubar.addAction(self.menuConfig.menuAction())
        self.toolBar.addAction(self.actionConnect)
        self.toolBar.addAction(self.actionReset)
        self.toolBar.addAction(self.actionProbe)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPan)
        self.toolBar.addAction(self.actionZoom)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPower_ON)
        self.toolBar.addAction(self.actionPower_OFF)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionGoto)
        self.toolBar.addAction(self.actionStopMotion)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionColor)
        self.toolBar.addAction(self.actionInit)
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addAction(self.actionPauseResume)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionViewConsole)
        self.toolBar.addAction(self.actionViewBootload)
        self.toolBar.addAction(self.actionViewParameters)
        self.toolBar.addAction(self.actionViewVariables)
        self.toolBar.addAction(self.actionViewDigital_Servos)
        self.toolBar.addAction(self.actionViewSettings)
        self.toolBar.addAction(self.actionViewGraphs)
        self.toolBar.addAction(self.actionViewSequencer)

        self.retranslateUi(imcc)
        QtCore.QMetaObject.connectSlotsByName(imcc)

    def retranslateUi(self, imcc):
        _translate = QtCore.QCoreApplication.translate
        imcc.setWindowTitle(_translate("imcc", "IgreBot\'s Mission Control Center"))
        self.menuConfig.setTitle(_translate("imcc", "Config"))
        self.toolBar.setWindowTitle(_translate("imcc", "IMCC ToolBar"))
        self.actionConnect.setText(_translate("imcc", "Connect"))
        self.actionConnect.setToolTip(_translate("imcc", "Connect to MCU"))
        self.actionConfigLoad.setText(_translate("imcc", "Load"))
        self.actionConfigSave.setText(_translate("imcc", "Save"))
        self.actionViewConsole.setText(_translate("imcc", "Console"))
        self.actionViewConsole.setToolTip(_translate("imcc", "Show / Hide consoles panel"))
        self.actionViewBootload.setText(_translate("imcc", "STm32 Bootload"))
        self.actionViewBootload.setToolTip(_translate("imcc", "Show / Hide Bootloader panel"))
        self.actionReset.setText(_translate("imcc", "Reset"))
        self.actionReset.setToolTip(_translate("imcc", "Reset the MCU"))
        self.actionProbe.setText(_translate("imcc", "Probe"))
        self.actionProbe.setToolTip(_translate("imcc", "Start / Stop probing"))
        self.actionViewParameters.setText(_translate("imcc", "Parameters"))
        self.actionViewParameters.setToolTip(_translate("imcc", "Show / Hide parameters panel"))
        self.actionViewVariables.setText(_translate("imcc", "Variables"))
        self.actionViewVariables.setToolTip(_translate("imcc", "Show / Hide Variables panel"))
        self.actionPan.setText(_translate("imcc", "Pan"))
        self.actionPan.setToolTip(_translate("imcc", "Switch to Pan mode"))
        self.actionGoto.setText(_translate("imcc", "Goto"))
        self.actionZoom.setText(_translate("imcc", "Zoom"))
        self.actionZoom.setToolTip(_translate("imcc", "Switch to Zoom mode"))
        self.actionStopMotion.setText(_translate("imcc", "Stop Motion"))
        self.actionStopMotion.setToolTip(_translate("imcc", "Cancel any motion"))
        self.actionColor.setText(_translate("imcc", "Match Color"))
        self.actionColor.setToolTip(_translate("imcc", "Select match color"))
        self.actionStart.setText(_translate("imcc", "Match Start"))
        self.actionStart.setToolTip(_translate("imcc", "Start the match sequence"))
        self.actionPauseResume.setText(_translate("imcc", "Match Pause"))
        self.actionPauseResume.setToolTip(_translate("imcc", "Pause (and resume) match sequence"))
        self.actionViewSettings.setText(_translate("imcc", "Settings"))
        self.actionViewSettings.setToolTip(_translate("imcc", "Show / Hide graphics settings"))
        self.actionViewGraphs.setText(_translate("imcc", "Graphics"))
        self.actionViewGraphs.setToolTip(_translate("imcc", "Show / Hide graphics windows"))
        self.actionViewDigital_Servos.setText(_translate("imcc", "Digital Servos"))
        self.actionViewDigital_Servos.setToolTip(_translate("imcc", "Show / Hide Digital Servos panel"))
        self.actionPower_ON.setText(_translate("imcc", "Power ON"))
        self.actionPower_OFF.setText(_translate("imcc", "Power OFF"))
        self.actionPower_OFF.setToolTip(_translate("imcc", "Power OFF"))
        self.actionStop.setText(_translate("imcc", "Match Stop"))
        self.actionStop.setToolTip(_translate("imcc", "Stop the match sequence"))
        self.actionInit.setText(_translate("imcc", "Match Init"))
        self.actionInit.setToolTip(_translate("imcc", "Initialize the match sequence"))
        self.actionViewSequencer.setText(_translate("imcc", "ViewSequencer"))
        self.actionViewSequencer.setToolTip(_translate("imcc", "Show / Hide sequencer panel"))
