# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sequencer.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Sequencer(object):
    def setupUi(self, Sequencer):
        Sequencer.setObjectName("Sequencer")
        Sequencer.resize(452, 383)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_match_state = QtWidgets.QLineEdit(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_match_state.sizePolicy().hasHeightForWidth())
        self.lineEdit_match_state.setSizePolicy(sizePolicy)
        self.lineEdit_match_state.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_match_state.setFont(font)
        self.lineEdit_match_state.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_match_state.setReadOnly(True)
        self.lineEdit_match_state.setObjectName("lineEdit_match_state")
        self.horizontalLayout.addWidget(self.lineEdit_match_state)
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_match_timer = QtWidgets.QLineEdit(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_match_timer.sizePolicy().hasHeightForWidth())
        self.lineEdit_match_timer.setSizePolicy(sizePolicy)
        self.lineEdit_match_timer.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_match_timer.setFont(font)
        self.lineEdit_match_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_match_timer.setReadOnly(True)
        self.lineEdit_match_timer.setObjectName("lineEdit_match_timer")
        self.horizontalLayout.addWidget(self.lineEdit_match_timer)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_match_points = QtWidgets.QLineEdit(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_match_points.sizePolicy().hasHeightForWidth())
        self.lineEdit_match_points.setSizePolicy(sizePolicy)
        self.lineEdit_match_points.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_match_points.setFont(font)
        self.lineEdit_match_points.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_match_points.setReadOnly(True)
        self.lineEdit_match_points.setObjectName("lineEdit_match_points")
        self.horizontalLayout.addWidget(self.lineEdit_match_points)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.pushButton_get_polys = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_get_polys.setObjectName("pushButton_get_polys")
        self.horizontalLayout_2.addWidget(self.pushButton_get_polys)
        self.pushButton_get_pois = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_get_pois.setObjectName("pushButton_get_pois")
        self.horizontalLayout_2.addWidget(self.pushButton_get_pois)
        self.pushButton_get_tasks = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_get_tasks.setObjectName("pushButton_get_tasks")
        self.horizontalLayout_2.addWidget(self.pushButton_get_tasks)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_5.setMinimumSize(QtCore.QSize(50, 0))
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.tableWidget_tasks = QtWidgets.QTableWidget(self.dockWidgetContents)
        self.tableWidget_tasks.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_tasks.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_tasks.setAlternatingRowColors(True)
        self.tableWidget_tasks.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_tasks.setColumnCount(6)
        self.tableWidget_tasks.setObjectName("tableWidget_tasks")
        self.tableWidget_tasks.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tasks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tasks.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tasks.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tasks.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tasks.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tasks.setHorizontalHeaderItem(5, item)
        self.tableWidget_tasks.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget_tasks.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_tasks.verticalHeader().setDefaultSectionSize(15)
        self.tableWidget_tasks.verticalHeader().setMinimumSectionSize(10)
        self.verticalLayout.addWidget(self.tableWidget_tasks)
        Sequencer.setWidget(self.dockWidgetContents)

        self.retranslateUi(Sequencer)
        QtCore.QMetaObject.connectSlotsByName(Sequencer)

    def retranslateUi(self, Sequencer):
        _translate = QtCore.QCoreApplication.translate
        Sequencer.setWindowTitle(_translate("Sequencer", "Sequencer"))
        self.label.setText(_translate("Sequencer", "State"))
        self.lineEdit_match_state.setText(_translate("Sequencer", "UNKNOWN"))
        self.label_2.setText(_translate("Sequencer", "Time"))
        self.lineEdit_match_timer.setText(_translate("Sequencer", "90"))
        self.label_3.setText(_translate("Sequencer", "Points"))
        self.lineEdit_match_points.setText(_translate("Sequencer", "0"))
        self.label_4.setText(_translate("Sequencer", "Actions"))
        self.pushButton_get_polys.setText(_translate("Sequencer", "Get PF\'s Polygons"))
        self.pushButton_get_pois.setText(_translate("Sequencer", "Get POIs"))
        self.pushButton_get_tasks.setText(_translate("Sequencer", "Get Tasks"))
        self.label_5.setText(_translate("Sequencer", "Tasks:"))
        item = self.tableWidget_tasks.horizontalHeaderItem(0)
        item.setText(_translate("Sequencer", "Name"))
        item = self.tableWidget_tasks.horizontalHeaderItem(1)
        item.setText(_translate("Sequencer", "State"))
        item = self.tableWidget_tasks.horizontalHeaderItem(2)
        item.setText(_translate("Sequencer", "Nb. Dep."))
        item = self.tableWidget_tasks.horizontalHeaderItem(3)
        item.setText(_translate("Sequencer", "Value"))
        item = self.tableWidget_tasks.horizontalHeaderItem(4)
        item.setText(_translate("Sequencer", "Priority"))
        item = self.tableWidget_tasks.horizontalHeaderItem(5)
        item.setText(_translate("Sequencer", "Trials"))

