# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stm32flash.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_stm32flash(object):
    def setupUi(self, stm32flash):
        stm32flash.setObjectName("stm32flash")
        stm32flash.resize(266, 321)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_config = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_config.setObjectName("groupBox_config")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_config)
        self.formLayout.setObjectName("formLayout")
        self.label_port = QtWidgets.QLabel(self.groupBox_config)
        self.label_port.setObjectName("label_port")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_port)
        self.comboBox_port = QtWidgets.QComboBox(self.groupBox_config)
        self.comboBox_port.setCurrentText("")
        self.comboBox_port.setObjectName("comboBox_port")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_port)
        self.label_mode = QtWidgets.QLabel(self.groupBox_config)
        self.label_mode.setObjectName("label_mode")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_mode)
        self.comboBox_mode = QtWidgets.QComboBox(self.groupBox_config)
        self.comboBox_mode.setCurrentText("")
        self.comboBox_mode.setObjectName("comboBox_mode")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_mode)
        self.label_baudrate = QtWidgets.QLabel(self.groupBox_config)
        self.label_baudrate.setObjectName("label_baudrate")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_baudrate)
        self.comboBox_baudrate = QtWidgets.QComboBox(self.groupBox_config)
        self.comboBox_baudrate.setCurrentText("")
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_baudrate)
        self.horizontalLayout_3.addWidget(self.groupBox_config)
        self.groupBox_options = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_options.setObjectName("groupBox_options")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_options)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_verify = QtWidgets.QCheckBox(self.groupBox_options)
        self.checkBox_verify.setChecked(True)
        self.checkBox_verify.setObjectName("checkBox_verify")
        self.verticalLayout.addWidget(self.checkBox_verify)
        self.checkBox_reset = QtWidgets.QCheckBox(self.groupBox_options)
        self.checkBox_reset.setChecked(True)
        self.checkBox_reset.setObjectName("checkBox_reset")
        self.verticalLayout.addWidget(self.checkBox_reset)
        self.checkBox_start = QtWidgets.QCheckBox(self.groupBox_options)
        self.checkBox_start.setObjectName("checkBox_start")
        self.verticalLayout.addWidget(self.checkBox_start)
        self.horizontalLayout_3.addWidget(self.groupBox_options)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_filename = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_filename.setObjectName("label_filename")
        self.horizontalLayout.addWidget(self.label_filename)
        self.lineEdit_filename = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.horizontalLayout.addWidget(self.lineEdit_filename)
        self.pushButton_browse = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.horizontalLayout.addWidget(self.pushButton_browse)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_write = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_write.setObjectName("pushButton_write")
        self.horizontalLayout_2.addWidget(self.pushButton_write)
        self.pushButton_erase = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_erase.setObjectName("pushButton_erase")
        self.horizontalLayout_2.addWidget(self.pushButton_erase)
        self.pushButton_read = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_read.setObjectName("pushButton_read")
        self.horizontalLayout_2.addWidget(self.pushButton_read)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_infos = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_infos.setObjectName("pushButton_infos")
        self.horizontalLayout_4.addWidget(self.pushButton_infos)
        self.pushButton_abort = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_abort.setObjectName("pushButton_abort")
        self.horizontalLayout_4.addWidget(self.pushButton_abort)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        stm32flash.setWidget(self.dockWidgetContents)

        self.retranslateUi(stm32flash)
        QtCore.QMetaObject.connectSlotsByName(stm32flash)

    def retranslateUi(self, stm32flash):
        _translate = QtCore.QCoreApplication.translate
        stm32flash.setWindowTitle(_translate("stm32flash", "STm32 Flash"))
        self.groupBox_config.setTitle(_translate("stm32flash", "Config"))
        self.label_port.setText(_translate("stm32flash", "Port"))
        self.label_mode.setText(_translate("stm32flash", "Mode"))
        self.label_baudrate.setText(_translate("stm32flash", "Baudrate"))
        self.groupBox_options.setTitle(_translate("stm32flash", "Options"))
        self.checkBox_verify.setText(_translate("stm32flash", "Verify"))
        self.checkBox_reset.setText(_translate("stm32flash", "Reset"))
        self.checkBox_start.setText(_translate("stm32flash", "Start"))
        self.label_filename.setText(_translate("stm32flash", "Filename"))
        self.pushButton_browse.setText(_translate("stm32flash", "Browse"))
        self.pushButton_write.setText(_translate("stm32flash", "Write"))
        self.pushButton_erase.setText(_translate("stm32flash", "Erase"))
        self.pushButton_read.setText(_translate("stm32flash", "Read"))
        self.pushButton_infos.setText(_translate("stm32flash", "Infos"))
        self.pushButton_abort.setText(_translate("stm32flash", "Abort"))

